name: Publish

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Weav.TaskScheduler/Weav.TaskScheduler.csproj
    - name: Build
      run: dotnet build --no-restore --configuration=Release ./src/Weav.TaskScheduler/Weav.TaskScheduler.csproj
    - name: Test
      run: dotnet test test/ --verbosity normal
    - name: Pack
      run: dotnet pack ./src/Weav.TaskScheduler/Weav.TaskScheduler.csproj --configuration=Release
    - name: Publish
      run: dotnet nuget push src/Weav.TaskScheduler/bin/Release/Weav.TaskScheduler.${{ steps.branch_name.outputs.SOURCE_TAG }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
