name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: why cant I find my project file
      run: ls -al
    - name: Restore dependencies
      run: dotnet restore src/Weav.TaskScheduler/Weav.TaskScheduler.csproj
    - name: Build
      run: dotnet build --no-restore src/Weav.TaskScheduler/Weav.TaskScheduler.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal test/
